# Site settings
title: xxiieao's blog
email: xxiieao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这里主要是我学习算法的笔记，以及一些杂谈
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xxiieao.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  xxiieao

# Build settings
markdown: kramdown
kramdown:
  input:  GFM
  use_coderay: true

paginate: 10